-- MWE requires db structure

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- DATABASE: `MWE`
--

CREATE TABLE IF NOT EXISTS `_ranges` (
`_id` int(11) NOT NULL,
  `_range_level` int(11) NOT NULL,
  `_name` varchar(25) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO `_ranges` (`_id`, `_range_level`, `_name`) VALUES
(0, 0, 'Guest');


CREATE TABLE IF NOT EXISTS `_user` (
  `_id` int(11) NOT NULL,
  `_name` varchar(25) NOT NULL,
  `_email` varchar(50) NOT NULL,
  `_range` int(11) NOT NULL DEFAULT '0',
  `_ban` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--
-- PRIMARY KEYS
--
ALTER TABLE `_ranges`
 ADD PRIMARY KEY (`_id`);

ALTER TABLE `_user`
 ADD PRIMARY KEY (`_id`);

 
--
-- AUTO INCREMENTS
--
ALTER TABLE `_ranges`
MODIFY `_id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
