-- MWE requires db structure

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- DATABASE: `MWE_security`
--

CREATE TABLE IF NOT EXISTS `security` (
`id` int(11) NOT NULL,
  `username` varchar(120) NOT NULL,
  `pass` varchar(500) NOT NULL,
  `semilla` varchar(120) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `sessions` (
`id` int(11) NOT NULL,
  `ip` varchar(15) CHARACTER SET utf8 NOT NULL COMMENT 'Client IP ',
  `nvar` varchar(2500) CHARACTER SET utf8 NOT NULL COMMENT 'Name of the session variable',
  `nval` varchar(2500) CHARACTER SET utf8 NOT NULL COMMENT 'Content of the session variable',
  `userid` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


--
-- PRIMARY KEYS
--
ALTER TABLE `security`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `sessions`
 ADD PRIMARY KEY (`id`);
 
--
-- AUTO INCREMENTS
--
ALTER TABLE `security`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

ALTER TABLE `sessions`
MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
